### ISSUE TITLE
Avatar self-view should rotate the camera view and not the character and his walking direction

### ISSUE THREAD

**Issue by johappel** [overte-org/overte#135]
When switching to the avatar self-view (keyboard > [2] ), not the camera but the character rotates, so that he unexpectedly walks backwards in this view.

Can this behavior be corrected?

**Comment by JulianGro** [comment]
I got to say that this has always bothered me as well.
And considering how often people walk backwards after changing the view, I believe we aren't the only two.

**Comment by ksuprynowicz** [comment]
Same here. Maybe we should add a setting for it?

**Comment by SilverfishVR** [comment]
> When switching to the avatar self-view (keyboard > [2] ), not the camera but the character rotates, so that he unexpectedly walks backwards in this view.

But it doesn't, your avatar keeps it's orientation regardless of camera change.
What is broken is that left/right yaw could be considered inverted in selfie mode (2) and strafing by holding by holding right mouse button should be inverted, since it is currently the opposite of strafing using "Q" or "E".
