### ISSUE TITLE
avatar entities don't always get deleted

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#544]
When creating an avatar entity through a script, it doesn't always disappear if the avatar that it belongs to itself disappears.

Here is an example script to do that:
```javascript
Entities.addEntity({
    type: "Sphere",
    position: MyAvatar.getJointPosition(2),
    dimensions: {x: 1, y: 1, z: 1},
    primitiveMode: "lines",
    visible: true,
    collisionless: true
}, "avatar");
```

**Comment by vegaslon** [comment]
Does it disappear to the viewer when they re enter domain?

**Comment by JulianGro** [comment]
Unfortunately not.
Even restarting doesn't make it disappear.
I also tried the alternative call:
```javascript
Entities.addEntity({
    type: "Sphere",
    position: MyAvatar.getJointPosition(2),
    dimensions: {x: 1, y: 1, z: 1},
    primitiveMode: "lines",
    visible: true,
    collisionless: true
}, true);
```

**Comment by JulianGro** [comment]
I think I might have just misunderstood the system.
Avatar entity data gets written to Interface.json which suggests that they follow you around until you delete them yourself.

**Comment by SilverfishVR** [comment]
This was always a thing, especially avatar entities that are parented to an avatar would pile up around the world 0.0.0 when people crashed because the reference coordinates changed from parent to world.

If you restart and leave an entity behind, your UUID won't match the `owningAvatarID` of the entity anymore  so really, it's no longer yours.
