### ISSUE TITLE
Pop out chat window

### ISSUE THREAD

**Issue by LimeProgramming** [overte-org/overte#898]
Would be nice if the chat window could pop out from the main game window in desktop mode like the create tab does just to get it out of the way. 

Thanks.

**Comment by vegaslon** [comment]
if anyone wants to do this it just uses https://apidocs.overte.org/Desktop.html

**Comment by Armored-Dragon** [comment]
[My chat app](https://github.com/overte-org/community-apps/tree/master/applications/armored-chat) does this currently, however until https://github.com/overte-org/community-apps/pull/75 gets merged, I wouldn't recommend it due to issue https://github.com/overte-org/overte/issues/824. The active pull request as a workaround.
